// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjuoxfddxdsygfnyzbex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdW94ZmRkeGRzeWdmbnl6YmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDkxMDcsImV4cCI6MjA2NTM4NTEwN30.oVLpCauZLUqBp71An7cB-OT6JZY5UDbeK7UKSRl9KQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});