// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxjvqrxntaulmkcgvasj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4anZxcnhudGF1bG1rY2d2YXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjQzNDUsImV4cCI6MjA2NjI0MDM0NX0.GLnR9pfcaImmgB6plz5xAM-kBnFYZqrCtgKiwIxaMzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});